input:
  names:
    - "tgt_x"
    - "tgt_y"
    - "tgt_z"
  types:
    - "Scalar"
    - "Scalar"
    - "Scalar"

output:
  names:
    - "error_x"
    - "error_y"
    - "error_z"
    - "laser"
  types:
    - "Scalar"
    - "Scalar"
    - "Scalar"
    - "Vector"
