input:
  names:
    - "tgt_x"
    - "tgt_y"
    - "tgt_z"
    - "tgt_pose"
  types:
    - "Scalar"
    - "Scalar"
    - "Scalar"
    - "Frame"

output:
  names:
    - "error_x"
    - "error_y"
    - "error_z"
    - "out_pose"
  types:
    - "Scalar"
    - "Scalar"
    - "Scalar"
    - "Frame"
